# Generated by Django 4.2.2 on 2023-06-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0003_alter_useraccounts_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('the_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.useraccounts')),
            ],
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.useraccounts')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.userpost')),
            ],
        ),
    ]
