# Generated by Django 4.2.2 on 2023-06-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='commment_upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
